### ISSUE TITLE
Изменить Readme

### ISSUE THREAD

**Issue by VadimCpp** [alisabox/events4friends-markup#1]
Сделать по аналогии с:
https://github.com/VadimCpp/six-cities

Разделы:

1. Задача. "Реализовать страницы сайта согласно макету (добавть ссылку на фигму)"
2. Кто здесь? Тут заказчик, исполнитель и дизайнер по аналогии
3. Демо. По аналогии. (Добавить картинку - перетянуть ее с рабочего стола прямо в поле ввода)
4. Как запустить код? По аналогии
5. Результат. "Этот мой первый коммерческий проект. Результат работы используется тут: https://events4friends.ru/ "

**Comment by alisabox** [comment]
Готово! 👍

**Comment by VadimCpp** [comment]
Добавь пожалуйста еще страницу ВК Давида: https://vk.com/d.sargs
В остальном - замечательно.

**Comment by alisabox** [comment]
Супер! Добавила!
